name: reg
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyyaml=6.0
  - yaml=0.2.5
  - pytest=7.3.1
  - verboselogs=1.7
  - numpy=1.25.0
  - sphinx
  - pip
  - pip:
    - sphinx_rtd_theme
