# This configuration file is used to run the basic suite of modelE
# regression tests. It is a required argument to mainDriver.py
modelconfig:
  model: modelE
  # Repository we are testing, usually a directory that contains a git repository.
  repository: https://github.com/dkouatch/hello_world.git
  #/discover/nobackup/bvanaart/giss/modele_testing/repos/E2.1_branch_traps
  # What branch. E.g master, planet, AR5_v2_branch
  repobranch: main
  # E2.1_branch
  #
  # Compilation type (release, debug (-O0 -g), traps)
  buildtype: traps
  #
  # Update the baseline (if different)
  updatebase: no
  #
  # Sort diffreport output - currently sorted by rundeck name
  sortdiff: yes

systemconfig:
  # Filesystem where we are doing all the work. If it does not exist, it will be created.
  # ***Using _traps suffix on directory so it will not overwrite regular E2.1 tests.
  scratchdir: /Users/deon.kouatchou/scratch
  # /discover/nobackup/projects/giss_ana/regression/modelE/E2.1_branch_traps
  #
  # Where we keep the regression scripts. Note that scripts are part of modelE code base.
  # Therefore, the scripts (and this file) are found under exec/testing directory.
  scriptsdir: /discover/nobackup/bvanaart/giss/modele_testing
  #
  # The following options are not commonly changed:
  # Use SLURM batch system on DISCOVER (NASA only)
  # If set to 'no', script (and commands therein) will run interactively.
  usebatch: yes
  #
  # sponsor ID required by SLURM
  sponsorid: s1001
  #
  # If we are using "modules" to load compilers then set to "yes"
  # NOTE: If modules=yes then specify/use modulelist in COMPCONFIG section
  # If set to 'no', scripts will use compilers available in the system.
  modules: yes
  #
  # Only for modelE: makeOld=in-source, makeNew=out-of-source with cmake (not yet working)
  makesystem: makeOld
  #
  # Path where we keep baseline answers. Used for verification.
  basedir: /discover/nobackup/modele/modelE_baseline
  #
  # Clean the regression testing scratch space (under scratchdir)
  cleanscratch: no
  # yes
  #
  # What compilers we support. Current choices are: intel, gfortran, gcc.
  compilers: intel
  # Specify version for each compiler: One-to-one with 'compilers' list above.
  # This information is *only* used in the final report.
  compiler_versions: 2021.3.0
  #
  # Specify names of module lists here. Note that the names in this list
  # must correspond to the ones referenced below.
  modulelist: intel_intelmpi
  # What each modulelist entry contains. Given names correspond to actual
  # module names on DISCOVER (or system being used).
  #intel_intelmpi=comp/intel/19.1.3.304,mpi/impi/19.1.3.304,mpi/impi-prov/19.1.3.304
  #intel_intelmpi=comp/intel/2021.3.0,mpi/impi/2021.3.0,mpi/impi-prov/2021.3.0
  intel_intelmpi: comp/intel/2021.3.0,mpi/impi/2021.3.0
  #gcc_openmpi=comp/gcc/9.3.0,mpi/hpcx/2.4.0
  #gcc_openmpi=comp/gcc/7.4.0,mpi/hpcx/2.4.0
  #gcc_openmpi=comp/gcc/8.3.0,mpi/hpcx/2.4.0
  #gcc_openmpi=comp/gcc/10.1.0,mpi/hpcx/2.4.0
  #gcc_openmpi=comp/gcc/10.1.0,mpi/openmpi/4.0.5/gcc-10.1.0
  #
  # The following variable names must correspond to the ones referenced in python
  # scripts.
  # intel paths
  intelnetcdf: /discover/nobackup/mkelley5/netcdf-4.7.1
  intelpnetcdf: /discover/nobackup/mkelley5/pnetcdf-1.11.2_sles12
  intelesmf:
  intelmpi: intel
  intelmpidir:
  intelserialpfunitdir:
  intelmpipfunitdir:
  # TODO: gcc paths
  gccnetcdf: /discover/nobackup/ccruz/Baselibs/modelE/netcdf4
  gccpnetcdf:
  gccesmf:
  gccmpi: openmpi
  #gccmpidir=/gpfsm/dulocal/sles12/mellanox/hpcx-v2.4.0-gcc-MLNX_OFED_LINUX-4.4-2.0.7.0-suse12.3-x86_64/ompi
  gccmpidir: /discover/swdev/gmao_SIteam/MPI/openmpi/4.0.5/gcc-10.1.0
  gccserialpfunitdir:
  gccmpipfunitdir:
  #
  # modelE settings (used to create .modelErc file):
  # Location of the modelE data (ICs,BCs)
  modeldatadir: /discover/nobackup/projects/giss/prod_input_files
  baselibdir:
  fvcubedroot:
  fftwroot:
  esmf: NO

reportconfig:
  # Where to mail tests report
  #mailto=giss-modele-regression@lists.nasa.gov
  mailto: deon.kouatchou@ssaihq.com
  #[ deon.kouatchou@ssaihq.com, jules.kouatchou-1@nasa.gov, bruce.vanaartsen@nasa.gov, carlos.a.cruz@nasa.gov ]
  # bruce.vanaartsen@nasa.gov
  #
  # Note: Email will also be sent to any addresses found in the "mailingList" file (in this
  # directory). This replaces the AMLS mailing system that no longer works.
  # Diffreport message (One sentence, no quotes)
  #
  message: Regression testing of modelE E2.1_branch using COMPILE_WITH_TRAPS
  #
  html: no
  # yes

# Rundeck configurations [run flag]
testcases:
  nonProduction_E_AR5_C12:
    compilers: intel
    modes: [ serial, mpi ]
    npes: [ 1, 4 ]
    verification: restartRun
    run: yes

  nonProduction_E4TcadC12:
    compilers: intel
    modes: serial,mpi
    npes: [ 1, 8 ]
    verification: restartRun

  EM20:
    compilers: intel
    modes: [ serial, mpi ]
    npes: [ 1, 4 ]
    verification: restartRun

  E1oM20:
    compilers: intel
    modes: [ serial,mpi ]
    npes: [ 1,4 ]
    verification: restartRun
    run: yes

  SGP4TESTS:
    compilers: intel
    modes: serial
    npes: 1
    verification: restartRun

  E6F40:
    compilers: intel
    modes: [serial,mpi]
    npes: 22
    verification: restartRun

  LLF40:
    compilers: intel
    modes: [serial,mpi]
    npes: 22
    verification: restartRun

  E6TlernerpsvF40:
    compilers: intel
    modes: [serial,mpi]
    npes: [1,8]
    verification: restartRun
    run: yes

  E_TdusNuF40:
    compilers: intel
    modes: [serial,mpi]
    npes: [1,8]
    verification: restartRun

  E6TvsdF40:
    compilers: intel
    modes: [serial,mpi]
    npes: [1,22]
    verification: restartRun

  E6TwisoF40:
    compilers: intel
    modes: [serial,mpi]
    npes: [1,22]
    verification: restartRun

  E6TomaF40:
    compilers: intel
    modes: mpi
    npes: 22
    verification: restartRun

  E6TomaF40int:
    compilers: intel
    modes: mpi
    npes: 22
    verification: restartRun

  R6TomaSSP585F40oQ40:
    compilers: intel
    modes: mpi
    npes: 88
    verification: restartRun

  E6TmatrixF40:
    compilers: intel
    modes: mpi
    npes: 44
    verification: restartRun
    run: yes

  E2.1_obio_v1:
    compilers: intel
    modes: mpi
    npes: 88
    verification: restartRun


################################################################################
# This  section specifies the computational environment including,
# if specified, the module lists and modelErc settings.
################################################################################
